backbone_config:
  type: VGG
  in_channels: 1
head:
  type: LSTMEncoderDecoder
val_transforms_list:
  - name: TransformGrayscale
device: "cuda"
model_path: /media/cluster_fs/user/vloginov/im2latex_project/0012/model_ctc_nan.pth
vocab_path: /media/cluster_fs/user/vloginov/im2latex_project/vocabs/vocab_alphanumeric.json
train:
  batch_size: 4
  learning_rate: 0.0001
  log_path: 0012/logs
  clip_grad: 1.0
  epochs: 10
  loss_type: CTC
  CTCLossZeroInf: true
  save_freq: 100000
  val_freq: 50000
  print_freq: 128
  optimizer: Adam
  save_dir: model_checkpoints
  datasets:
    - type: MJSynthDataset
      data_folder: /media/cluster_fs/user/vloginov/im2latex_project/90kDICT32px
      annotation_file: annotation_toy.txt
      case_sensitive: false
      fixed_img_shape:
        - 32
        - 120
      subset: train
    - type: ICDAR2013RECDataset
      case_sensitive: false
      images_folder: Challenge2_Training_Task3_Images
      annotation_file: Challenge2_Training_Task3_Images/gt.txt
      root: /media/cluster_fs/user/vloginov/im2latex_project
      fixed_img_shape:
        - 32
        - 120
      grayscale: true
      subset: validate
  train_transforms_list:
    - name: TransformGrayscale
