name: mobilenet-v2-w1-imagenet
domain: Image classification
problem: ImageNet classification
framework: OTEReidentification v1.2.3
summary: Imagenet classification based on MobileNet-V2.
annotation_format: CustomImages
dependencies:
- sha256: 447d0b5cf0aee0d901c270925b8448099c4f69149b4f04f80231188a6b4c8e10
  size: 14214917
  source: https://drive.google.com/uc?export=download&id=1PrLdWkgxwMuf5JT9pZMEIqwco0qbcDBP
  destination: snapshot.pth
- source: ../../../../../pytorch_toolkit/ote/tools/train.py
  destination: train.py
- source: ../../../../../pytorch_toolkit/ote/tools/eval.py
  destination: eval.py
- source: ../../../../../pytorch_toolkit/ote/tools/export.py
  destination: export.py
- source: ../../../../../pytorch_toolkit/ote/tools/compress.py
  destination: compress.py
- source: ../../../../../pytorch_toolkit/ote
  destination: packages/ote
- source: ../../requirements.txt
  destination: requirements.txt
max_nodes: 1
training_target:
- GPU
- CPU
inference_target:
- CPU
- iGPU
hyper_parameters:
  basic:
    batch_size: 256
    base_learning_rate: 0.1
    epochs: 150
output_format:
  onnx:
    default: true
  openvino:
    default: true
    input_format: BGR
compression: null
metrics:
- display_name: Size
  key: size
  unit: Mp
  value: 3.504
- display_name: Complexity
  key: complexity
  unit: GFLOPs
  value: 0.659
- display_name: Top-1 accuracy
  key: accuracy
  unit: '%'
  value: 73.03
gpu_num: 2
tensorboard: true
config: model.yaml
